# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-15 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=20)),
                ('Product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Product_color', models.CharField(max_length=20)),
            ],
        ),
    ]
