# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-21 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('empname', models.CharField(max_length=20)),
                ('empsal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
