# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-18 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewsetApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(help_text='Name is required', max_length=200),
        ),
    ]
