# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-24 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=20)),
                ('semail', models.EmailField(max_length=50)),
                ('sfee', models.IntegerField()),
                ('sloc', models.CharField(max_length=20)),
            ],
        ),
    ]
