# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-06 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=20)),
                ('Product_price', models.IntegerField()),
                ('Product_color', models.CharField(max_length=20)),
            ],
        ),
    ]
